= Structural selections for Kakoune

kak-tree is a plugin for Kakoune which enables selection of syntax tree nodes. Parsing is performed with https://github.com/tree-sitter/tree-sitter[tree-sitter].

Status: proof of concept.

== Installation

Replace `"rust javascript"` with a list of languages you need. Or use `all` to build all supported
languages. Note that `all` build takes a long time, and resulting binary is quite fat which could
have a negative impact on responsiveness.

----
git clone --recurse-submodules
cargo build --release --features "rust javascript"
cargo install
cp rc/tree.kak ~/.config/kak/autoload/
----

Look at `Cargo.toml` for a full list of supported languages.

== Usage

NOTE: "The deepest enclosing node" means the one which matters. For now it's so-called named
node (it's named in tree-sitter grammar definition for the given language), and in future custom
white/balcklisting will be supported on top of that.

[cols=2*]
|===
| tree-select-node
| Extend selections to the deepest enclosing nodes. If any selection is equal to node range, then
extend to one's parent range.

| tree-select-next-node
| Extend selections to the deepest enclosing nodes' next siblings.

| tree-select-prev-node
| Extend selections to the deepest enclosing nodes' previous siblings.

| tree-node-sexp
| Show info box with a syntax tree of the deepest enclosing node of the main selection. This time
"deepest" means "deepest", including anonymous and blacklisted nodes, without any filter applied.
|===

More commands to come.

== License

For kak-tree see UNLICENSE file. For tree-sitter and its parsers look at their repositories.
